#include "src/game/envfx_snow.h"

const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Half_Closed_Eyes__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Closed_Eyes__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Left_Eyes__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Right_Eyes__SKIN__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Up_Eyes__SKIN__6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Down_Eyes__SKIN__7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Dead_Eyes__SKIN__8),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1),
			GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2),
			GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3),
			GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4),
			GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5),
			GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6),
			GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, sybil_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, sybil_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, sybil_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Half_Closed_Eyes__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Closed_Eyes__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Left_Eyes__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Right_Eyes__SKIN__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Up_Eyes__SKIN__6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Down_Eyes__SKIN__7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Dead_Eyes__SKIN__8),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sybil_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1),
			GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2),
			GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3),
			GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4),
			GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5),
			GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6),
			GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sybil_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, sybil_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sybil_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, sybil_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sybil_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, sybil_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 22, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 35449),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sybil_Butt_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_move_mario_part_from_parent),
					GEO_ASM(0, geo_mario_tilt_torso),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, sybil_Torso_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 138, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_head_rotation),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Head_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sybil_Capless_Head),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, 100, -45, 73, -17, 29, -134),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Left_Wing_DL_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, 100, -45, -73, 17, -29, -134),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Right_Wing_DL_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 81, -10, 77, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sybil_Left_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Left_Forearm_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 76, 0, 0, sybil_Left_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, -2),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Left_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sybil_Left_Hand_Open),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 82, -10, -74, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sybil_Right_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Right_Forearm_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 76, 0, 0, sybil_Right_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, -2),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Right_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sybil_Right_Hand_Open),
											GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sybil_Right_Hand_Peace),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -8, -8, 72, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sybil_Left_Thigh_Color_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Left_Leg_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 151, 0, 0, sybil_Left_Leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 137, 0, 0, sybil_Left_Shoe_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -8, -8, -58, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sybil_Right_Thigh_Color_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Right_Leg_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 151, 0, 0, sybil_Right_Leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 137, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Right_Shoe_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_sybil_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_sybil_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, sybil_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_sybil_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, sybil_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_sybil_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, sybil_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 22, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 35449),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sybil_Butt_mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_move_mario_part_from_parent),
					GEO_ASM(0, geo_mario_tilt_torso),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, sybil_Torso_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 138, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_head_rotation),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Head_DL_mesh_layer_1_mat_override_Metal__METAL__0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_sybil_Capless_Head),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, 100, -45, 73, -17, 29, -134),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_ALPHA, sybil_Left_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, 100, -45, -73, 17, -29, -134),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_ALPHA, sybil_Right_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 81, -10, 77, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sybil_Left_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Left_Forearm_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 0, 0, sybil_Left_Forearm_mesh_layer_1_mat_override_Metal__METAL__0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, -2),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Left_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_sybil_Left_Hand_Open),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 82, -10, -74, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sybil_Right_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Right_Forearm_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 0, 0, sybil_Right_Forearm_mesh_layer_1_mat_override_Metal__METAL__0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, -2),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Right_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_sybil_Right_Hand_Open),
											GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_sybil_Right_Hand_Peace),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -8, -8, 72, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sybil_Left_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Left_Leg_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 151, 0, 0, sybil_Left_Leg_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 137, 0, 0, sybil_Left_Shoe_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -8, -8, -58, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sybil_Right_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Right_Leg_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 151, 0, 0, sybil_Right_Leg_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 137, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Right_Shoe_DL_mesh_layer_1_mat_override_Metal__METAL__0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_sybil_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Metal__METAL__1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_sybil_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, sybil_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_sybil_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, sybil_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_sybil_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, sybil_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal__METAL__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 22, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 35449),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sybil_Butt_mesh_layer_1_mat_override_Metal__METAL__1),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_move_mario_part_from_parent),
					GEO_ASM(0, geo_mario_tilt_torso),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, sybil_Torso_mesh_layer_1_mat_override_Metal__METAL__1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 138, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_head_rotation),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Head_DL_mesh_layer_1_mat_override_Metal__METAL__1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_sybil_Capless_Head),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, 100, -45, 73, -17, 29, -134),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Left_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, 100, -45, -73, 17, -29, -134),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Right_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 81, -10, 77, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sybil_Left_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Left_Forearm_skinned_mesh_layer_1_mat_override_Metal__METAL__1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 76, 0, 0, sybil_Left_Forearm_mesh_layer_1_mat_override_Metal__METAL__1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, -2),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Left_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_sybil_Left_Hand_Open),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 82, -10, -74, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sybil_Right_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Right_Forearm_skinned_mesh_layer_1_mat_override_Metal__METAL__1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 76, 0, 0, sybil_Right_Forearm_mesh_layer_1_mat_override_Metal__METAL__1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, -2),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Right_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__1),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_sybil_Right_Hand_Open),
											GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_sybil_Right_Hand_Peace),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -8, -8, 72, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sybil_Left_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Left_Leg_skinned_mesh_layer_1_mat_override_Metal__METAL__1),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 151, 0, 0, sybil_Left_Leg_mesh_layer_1_mat_override_Metal__METAL__1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 137, 0, 0, sybil_Left_Shoe_mesh_layer_1_mat_override_Metal__METAL__1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -8, -8, -58, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sybil_Right_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Right_Leg_skinned_mesh_layer_1_mat_override_Metal__METAL__1),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 151, 0, 0, sybil_Right_Leg_mesh_layer_1_mat_override_Metal__METAL__1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 137, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sybil_Right_Shoe_DL_mesh_layer_1_mat_override_Metal__METAL__1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sybil_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(99, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 30290),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE_DECAL + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT_DECAL + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_OPAQUE_DECAL << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT_DECAL << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 22, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_SCALE(LAYER_FORCE, 35449),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sybil_Butt_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_move_mario_part_from_parent),
											GEO_ASM(0, geo_mario_tilt_torso),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, sybil_Torso_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 138, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_head_rotation),
														GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Head_DL_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, sybil_Capless_Head),
															GEO_CLOSE_NODE(),
															GEO_TRANSLATE_ROTATE(LAYER_FORCE, 100, -45, 73, -17, 29, -134),
															GEO_OPEN_NODE(),
																GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
																GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_ALPHA, sybil_Left_Wing_DL_mesh_layer_4),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_TRANSLATE_ROTATE(LAYER_FORCE, 100, -45, -73, 17, -29, -134),
															GEO_OPEN_NODE(),
																GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
																GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_ALPHA, sybil_Right_Wing_DL_mesh_layer_4),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 81, -10, 77, NULL),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sybil_Left_Arm_Color_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Left_Forearm_skinned_mesh_layer_1),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 0, 0, sybil_Left_Forearm_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(1, geo_switch_mario_hand),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, -2),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
																			GEO_OPEN_NODE(),
																				GEO_ASM(1, geo_mario_hand_foot_scaler),
																				GEO_SCALE(LAYER_FORCE, 65536),
																				GEO_OPEN_NODE(),
																					GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Left_Hand_DL_mesh_layer_1),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, sybil_Left_Hand_Open),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 82, -10, -74, NULL),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sybil_Right_Arm_Color_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Right_Forearm_skinned_mesh_layer_1),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 0, 0, sybil_Right_Forearm_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_hand),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, -2),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
																			GEO_OPEN_NODE(),
																				GEO_ASM(0, geo_mario_hand_foot_scaler),
																				GEO_SCALE(LAYER_FORCE, 65536),
																				GEO_OPEN_NODE(),
																					GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Right_Hand_DL_mesh_layer_1),
																				GEO_CLOSE_NODE(),
																				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, sybil_Right_Hand_Open),
																	GEO_BRANCH(1, sybil_Right_Hand_Peace),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -8, -8, 72, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sybil_Left_Thigh_Color_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Left_Leg_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 151, 0, 0, sybil_Left_Leg_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 137, 0, 0, sybil_Left_Shoe_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -8, -8, -58, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sybil_Right_Thigh_Color_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Right_Leg_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 151, 0, 0, sybil_Right_Leg_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 137, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(2, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, sybil_Right_Shoe_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt1),
							GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt2),
							GEO_BRANCH(1, sybil_B_LoD_Switch_opt0_Cap_State_Switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_OPAQUE_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
